### ISSUE TITLE
Use the .env file on .gitlab-ci for the build-image job

### ISSUE THREAD

**Issue by mathieu-ducrot** [smartbooster/symfony-docker#8]
## Goal

Stop manualy pass the value of the language version and instead rely on the value from the .env file

```yaml
build-image:
  stage: build-test
  image: docker
  services:
    - docker:dind 
  variables:
    # Replace manual variable with the use of the .env file
    PHP_VERSION: '8.1'
    NODE_VERSION: '18'
  script:
    - echo $PHP_VERSION
    - echo $NODE_VERSION
    - docker build --build-arg PHP_VERSION=$PHP_VERSION --build-arg NODE_VERSION=$NODE_VERSION -t 
```

## Technique

Try the `env $(cat .env | grep -v '^#')` instruction prior to the docker build step
